services:
  api:
    image: 700030737976.dkr.ecr.eu-west-3.amazonaws.com/rag-api:latest
    env_file: .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    logging:
      driver: awslogs
      options:
        awslogs-group: /rag/api
        awslogs-region: eu-west-3
        awslogs-stream: ecs

  streamlit:
    image: 700030737976.dkr.ecr.eu-west-3.amazonaws.com/rag-ui:latest
    env_file: .env
    ports:
      - "8501:8501"
    logging:
      driver: awslogs
      options:
        awslogs-group: /rag/streamlit
        awslogs-region: eu-west-3
        awslogs-stream: ecs

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    logging:
      driver: awslogs
      options:
        awslogs-group: /rag/qdrant
        awslogs-region: eu-west-3
        awslogs-stream: ecs

volumes:
  qdrant_data: